#----------------------------------
# npm build part
#----------------------------------
FROM node:16 as sform-ui-builder
ARG GITHUB_TOKEN

RUN git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/macorains/sform2-config.git && \
    git clone https://github.com/macorains/sform-ui.git && \
    cd sform-ui && \
    cp ../sform2-config/sform-ui/prod.env.js config/prod.env.js && \
    npm install --force && \
    npm run build_prod

#----------------------------------
# nginx deploy part
#----------------------------------
FROM nginx:latest

COPY --from=sform-ui-builder /sform-ui/dist/ /usr/share/nginx/html/
